// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjScSiFenSR1AUylUm_z_vojTjUioqojE',
    appId: '1:560073561053:web:f8a49fbf340a08efe15c34',
    messagingSenderId: '560073561053',
    projectId: 'nokodo-8b4e0',
    authDomain: 'nokodo-8b4e0.firebaseapp.com',
    storageBucket: 'nokodo-8b4e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCspLX5-BQlrJyOsLZUJ5Ia2LjHpkPPv1I',
    appId: '1:560073561053:android:d2823711697dfec3e15c34',
    messagingSenderId: '560073561053',
    projectId: 'nokodo-8b4e0',
    storageBucket: 'nokodo-8b4e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjmvtk7MshfWHWO-Nx9BSR7VHDGeFkxk',
    appId: '1:560073561053:ios:30fe46b6c5e45c51e15c34',
    messagingSenderId: '560073561053',
    projectId: 'nokodo-8b4e0',
    storageBucket: 'nokodo-8b4e0.firebasestorage.app',
    iosBundleId: 'com.example.nodyslexia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjmvtk7MshfWHWO-Nx9BSR7VHDGeFkxk',
    appId: '1:560073561053:ios:30fe46b6c5e45c51e15c34',
    messagingSenderId: '560073561053',
    projectId: 'nokodo-8b4e0',
    storageBucket: 'nokodo-8b4e0.firebasestorage.app',
    iosBundleId: 'com.example.nodyslexia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjScSiFenSR1AUylUm_z_vojTjUioqojE',
    appId: '1:560073561053:web:d724c5a73db1c901e15c34',
    messagingSenderId: '560073561053',
    projectId: 'nokodo-8b4e0',
    authDomain: 'nokodo-8b4e0.firebaseapp.com',
    storageBucket: 'nokodo-8b4e0.firebasestorage.app',
  );
}
